/**
 * Three.js rendering of the 3x3x3 cube.
 *
 * Each cubie keeps its own logical state:
 *   pos  - current grid coordinate in {-1,0,1}^3
 *   ori  - ori[worldFace] = which of the cubie's six glued stickers faces that
 *          world direction right now (a rotation permutation)
 * The view's state evolves in lockstep with the solver model, so
 * `setFacelets` can paint the model's facelet string straight onto the current
 * visible stickers. `resetPositions` snaps everything back to the canonical
 * solved grid and is only used when the model itself is reset.
 */

import * as THREE from 'three';
import { FACE_NORMAL as FN, FACE_COLORS_HEX, FACE_AXIS, FACE_LAYER, FACE_ANGLE } from './facemeta.js';
import { OrbitCamera } from './orbitcamera.js';

export const FACE_COLORS = FACE_COLORS_HEX;
export const FACE_LABELS = ['U', 'R', 'F', 'D', 'L', 'B'];

const NRM = FN.map((v) => new THREE.Vector3(v[0], v[1], v[2]));
const AXIS_VEC = [new THREE.Vector3(1, 0, 0), new THREE.Vector3(0, 1, 0), new THREE.Vector3(0, 0, 1)];
const PALETTE = FACE_COLORS_HEX;
const GREY = 0x505050;

export function visibleFaces(x, y, z) {
  const f = [];
  if (y === 1) f.push(0);
  if (x === 1) f.push(1);
  if (z === 1) f.push(2);
  if (y === -1) f.push(3);
  if (x === -1) f.push(4);
  if (z === -1) f.push(5);
  return f;
}

export function faceletIndex(x, y, z, face) {
  let col, row;
  switch (face) {
    case 0: col = x + 1; row = z + 1; break;
    case 1: col = 1 - z; row = 1 - y; break;
    case 2: col = x + 1; row = 1 - y; break;
    case 3: col = x + 1; row = 1 - z; break;
    case 4: col = z + 1; row = 1 - y; break;
    case 5: col = 1 - x; row = 1 - y; break;
    default: col = 0; row = 0;
  }
  return face * 9 + row * 3 + col;
}

/* ---------------- rotation helpers ---------------- */

/** Rotate a vector by `quarter` right-handed quarter turns about +axis k. */
export function rotVec(p, k, quarter) {
  const v = p.clone();
  const n = ((quarter % 4) + 4) % 4;
  for (let i = 0; i < n; i++) {
    const { x, y, z } = v;
    if (k === 0) v.set(x, -z, y);
    else if (k === 1) v.set(z, y, -x);
    else v.set(-y, x, z);
  }
  return v;
}

/**
 * Snap a grid coordinate to the slot it lands in after `quarter` quarter turns
 * about +axis k, as a plain [x,y,z] array.
 *
 * This is the ONE place a landed turn changes a cubie's position. `quarter` may
 * be negative (turnQuarter returns -1 for U/R/F clockwise and for D/L/B
 * counter-clockwise), so it is normalised to 0..3 first — a loop written as
 * `for (i = 0; i < quarter; i++)` silently does nothing for every negative
 * quarter, which leaves `pos` stale while `ori` still advances and produces
 * bare, colourless faces.
 */
export function advanceSlot(pos, k, quarter) {
  const n = ((quarter % 4) + 4) % 4;
  let [x, y, z] = pos;
  for (let i = 0; i < n; i++) {
    if (k === 0) { const t = y; y = -z; z = t; }
    else if (k === 1) { const t = x; x = z; z = -t; }
    else { const t = x; x = -y; y = t; }
  }
  return [x, y, z];
}

/** face index whose normal matches v (v must be a unit axis). */
function faceOfNormal(v) {
  for (let f = 0; f < 6; f++) {
    if (Math.abs(NRM[f].x - v.x) < 1e-6 && Math.abs(NRM[f].y - v.y) < 1e-6 && Math.abs(NRM[f].z - v.z) < 1e-6) return f;
  }
  return -1;
}

/** face permutation for one face turn: P[oldWorldFace] = newWorldFace. */
export function facePermutation(k, quarter) {
  const P = new Array(6);
  for (let f = 0; f < 6; f++) P[f] = faceOfNormal(rotVec(NRM[f], k, quarter));
  return P;
}

/**
 * The 24 axis-aligned orientations of a cube, as quaternions.
 * Generated by closing {identity} under the three 90-degree rotations.
 */
const CUBE_QUATS = (() => {
  const base = AXIS_VEC.map((v) => new THREE.Quaternion().setFromAxisAngle(v, Math.PI / 2));
  const key = (q) => [q.x, q.y, q.z, q.w].map((v) => Math.round(v * 1e4)).join(',');
  const out = [];
  const seen = new Set();
  const start = new THREE.Quaternion();
  const queue = [start];
  seen.add(key(start));
  out.push(start);
  while (queue.length) {
    const q = queue.shift();
    for (const b of base) {
      const n = q.clone().multiply(b);
      const k = key(n);
      if (!seen.has(k)) { seen.add(k); out.push(n); queue.push(n); }
    }
  }
  return out;
})();

/**
 * Snap a quaternion to the nearest exact cube orientation.
 *
 * Cubie orientations are only ever one of 24 rotations, but baking a turn into
 * a quaternion each move accumulates float drift. Snapping keeps the sticker
 * meshes exactly axis aligned (no seams, no creeping tilt) and keeps
 * faceOfHit / audit comparisons exact.
 */
function snapQuaternion(q) {
  let best = CUBE_QUATS[0], bestDot = -Infinity;
  for (const c of CUBE_QUATS) {
    /* q and -q are the same rotation, hence the absolute value */
    const d = Math.abs(q.x * c.x + q.y * c.y + q.z * c.z + q.w * c.w);
    if (d > bestDot) { bestDot = d; best = c; }
  }
  return best.clone();
}

/** quarter turns of a face turn about its positive axis. */
export function turnQuarter(face, amount) {
  const positive = FACE_LAYER[face] > 0;
  if (amount === 2) return 2;
  const cw = amount === 1;
  return positive ? (cw ? -1 : 1) : (cw ? 1 : -1);
}

export class CubeView {
  constructor(container) {
    this.container = container;
    this.scene = new THREE.Scene();
    /* Unlimited orbit camera: orientation is a quaternion, so there is no polar
     * angle to clamp and the view can keep rotating in any direction. */
    this.orbitCamera = new OrbitCamera({ fov: 42, aspect: 1, near: 0.1, far: 200 });
    this.camera = this.orbitCamera.camera;
    this.renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    this.renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));
    container.appendChild(this.renderer.domElement);

    this.scene.add(new THREE.AmbientLight(0xffffff, 1.45));
    const k = new THREE.DirectionalLight(0xffffff, 1.5); k.position.set(7, 11, 9); this.scene.add(k);
    const f = new THREE.DirectionalLight(0xffffff, 0.8); f.position.set(-8, -6, -7); this.scene.add(f);
    const s = new THREE.DirectionalLight(0xffffff, 0.5); s.position.set(-6, 8, -8); this.scene.add(s);

    this.root = new THREE.Group();
    this.scene.add(this.root);

    this.cubies = [];
    this.build();


    this.queue = [];
    this.anim = null;
    this.onMoveDone = null;

    this._onResize = () => this.resize();
    window.addEventListener('resize', this._onResize);
    this.resize();
  }

  build() {
    const bodyGeo = new THREE.BoxGeometry(0.96, 0.96, 0.96);
    const bodyMat = new THREE.MeshStandardMaterial({ color: 0x0e1015, roughness: 0.85, metalness: 0.02 });
    const stickerGeo = new THREE.PlaneGeometry(0.8, 0.8);
    this.stickerGeo = stickerGeo;

    for (let x = -1; x <= 1; x++) for (let y = -1; y <= 1; y++) for (let z = -1; z <= 1; z++) {
      const g = new THREE.Group();
      g.add(new THREE.Mesh(bodyGeo, bodyMat));
      const mats = new Array(6).fill(null);
      for (const face of visibleFaces(x, y, z)) {
        const mat = new THREE.MeshStandardMaterial({ color: PALETTE[face], roughness: 0.4, metalness: 0.03 });
        const st = new THREE.Mesh(stickerGeo, mat);
        const n = FN[face];
        st.position.set(n[0] * 0.485, n[1] * 0.485, n[2] * 0.485);
        st.lookAt(n[0] * 3, n[1] * 3, n[2] * 3);
        g.add(st);
        mats[face] = mat;
      }
      g.position.set(x, y, z);
      g.userData = {
        pos: [x, y, z],
        home: [x, y, z],           // canonical grid slot — never mutated
        ori: [0, 1, 2, 3, 4, 5],   // ori[worldFace] = stickerFace
        mats,
        stickers: mats,            // picking marker + back-compat
      };
      this.root.add(g);
      this.cubies.push(g);
    }
  }

  resize() {
    const w = this.container.clientWidth || 640;
    const h = this.container.clientHeight || 480;
    this.renderer.setSize(w, h, false);
    this.camera.aspect = w / h;
    this.camera.updateProjectionMatrix();
  }

  /* Camera control is delegated to OrbitCamera. There is deliberately NO polar
   * clamp here: dragging up or down keeps rotating the view past the top,
   * instead of stopping dead at a pole. */
  orbit(dx, dy) { this.orbitCamera.orbit(dx, dy); }

  zoom(d) { this.orbitCamera.zoom(d); }

  setView(theta, phi) { this.orbitCamera.setView(theta, phi); }

  updateCamera() { this.orbitCamera.update(); }

  /** Paint a 54-char facelet string onto the currently visible stickers. */
  setFacelets(fl) {
    for (const g of this.cubies) {
      const { pos, ori, mats } = g.userData;
      for (const w of visibleFaces(pos[0], pos[1], pos[2])) {
        const mat = mats[ori[w]];
        if (!mat) continue;
        const idx = 'URFDLB'.indexOf(fl[faceletIndex(pos[0], pos[1], pos[2], w)]);
        mat.color.setHex(idx >= 0 ? PALETTE[idx] : GREY);
      }
    }
  }

  /** Re-snap every cubie onto its current logical slot, clearing a partial
   *  animation. Does NOT undo any landed move — see resetToSolved for that. */
  resetPositions() {
    for (const g of this.cubies) {
      const { pos } = g.userData;
      g.position.set(pos[0], pos[1], pos[2]);
      g.quaternion.identity();
    }
  }

  /**
   * Hard reset: every cubie returns to its CANONICAL grid slot (`home`) with
   * identity orientation, then the stickers are painted.
   *
   * Using `home` rather than the current `pos` is essential. After a scramble
   * `pos` holds a permutation; re-snapping to it while resetting `ori` to the
   * identity would leave the geometry scrambled but the orientation bookkeeping
   * naive, so any sticker that no longer points at a direction its cubie
   * originally showed would become a hole (a bare, dark body face).
   */
  resetToSolved(fl) {
    for (const g of this.cubies) {
      const { home } = g.userData;
      g.userData.pos = [home[0], home[1], home[2]];
      g.userData.ori = [0, 1, 2, 3, 4, 5];
      g.position.set(home[0], home[1], home[2]);
      g.quaternion.identity();
    }
    if (fl) this.setFacelets(fl);
  }

  /**
   * Self-check: compare what the view is currently showing against a model
   * facelet string.
   *
   *   holes      - visible directions whose sticker mesh is missing/wrong
   *                (renders as a dark patch instead of a colour)
   *   mismatched - stickers painted a different colour than the model asks for
   *   checks     - visible directions examined
   *
   * A healthy view has holes === 0 && mismatched === 0.
   */
  audit(fl) {
    this.root.updateMatrixWorld(true);
    let holes = 0, mismatched = 0, checks = 0;
    const tmpQ = new THREE.Quaternion();
    const tmpN = new THREE.Vector3();

    for (const g of this.cubies) {
      const { pos, mats } = g.userData;

      /* Which sticker mesh PHYSICALLY faces each world direction right now.
       * Derived from the scene graph, not from `ori` — a check that consults
       * `ori` would agree with setFacelets by construction and could never
       * detect a mesh that is missing or pointing the wrong way. */
      const here = new Map();
      for (const child of g.children) {
        if (!child.isMesh) continue;
        if (!mats.includes(child.material)) continue;   // skip the black body box
        child.getWorldQuaternion(tmpQ);
        tmpN.set(0, 0, 1).applyQuaternion(tmpQ);
        let best = -1, bestDot = 0.5;
        for (let f = 0; f < 6; f++) {
          const d = tmpN.x * FN[f][0] + tmpN.y * FN[f][1] + tmpN.z * FN[f][2];
          if (d > bestDot) { bestDot = d; best = f; }
        }
        if (best >= 0) here.set(best, child);
      }

      for (const w of visibleFaces(pos[0], pos[1], pos[2])) {
        checks++;
        const idx = 'URFDLB'.indexOf(fl[faceletIndex(pos[0], pos[1], pos[2], w)]);
        if (idx < 0) { holes++; continue; }
        const st = here.get(w);
        if (!st) { holes++; continue; }
        if (st.material.color.getHex() !== PALETTE[idx]) mismatched++;
      }
    }
    return { holes, mismatched, checks };
  }

  /**
   * Queue a turn. `opts.onDone(move)` fires when THAT move lands — the callback
   * travels with the queued item, so a batch of moves each gets its own
   * notification instead of only the last one.
   */
  enqueue(move, opts = {}) { this.queue.push({ move, ms: opts.ms ?? 150, onDone: opts.onDone || null }); }
  enqueueAll(moves, opts = {}) { for (const m of moves) this.enqueue(m, opts); }
  clearQueue() { this.queue.length = 0; }

  /**
   * Abort everything in flight: drop the queue AND snap a partially animated
   * layer back to its starting orientation before the caller resets positions.
   * No callback is invoked, so no half-applied move ever reaches the model.
   */
  cancelAll() {
    this.queue.length = 0;
    if (this.anim) {
      const { group, affected } = this.anim;
      group.remove(...affected);
      this.root.add(...affected);
      for (const g of affected) {
        const { pos } = g.userData;
        g.position.set(pos[0], pos[1], pos[2]);
        g.quaternion.identity();
      }
      this.anim = null;
    }
  }

  get busy() { return this.anim !== null || this.queue.length > 0; }

  startMove(move, ms, onDone) {
    const axisIdx = FACE_AXIS[move.face];
    const layer = FACE_LAYER[move.face];
    const q = FACE_ANGLE[move.face];
    const angle = move.amount === 2 ? Math.PI * Math.sign(q) : q * (move.amount === 1 ? 1 : -1);

    const group = new THREE.Group();
    this.root.add(group);
    const affected = [];
    for (const g of this.cubies) {
      if (g.userData.pos[axisIdx] === layer) affected.push(g);
    }
    for (const g of affected) group.add(g);

    this.anim = { group, axis: AXIS_VEC[axisIdx], to: angle, start: performance.now(), ms, move, affected, onDone: onDone || null };
  }

  /** Snap the turned layer onto the grid, advancing pos and ori. */
  finishMove() {
    const { group, affected, move } = this.anim;
    const k = FACE_AXIS[move.face];
    const q = turnQuarter(move.face, move.amount);
    const P = facePermutation(k, q);

    /* The rotation the user just watched. It must be BAKED into each cubie:
     * the sticker meshes are children glued at fixed local positions, and the
     * temporary animation group is discarded on re-parent, so its rotation is
     * otherwise lost. Resetting to identity here leaves the meshes pointing at
     * their build orientation while `ori` still claims they turned — which
     * paints the wrong mesh and leaves bare dark faces. */
    const qTurn = new THREE.Quaternion().setFromAxisAngle(AXIS_VEC[k], q * Math.PI / 2);

    for (const g of affected) {
      const { pos, ori } = g.userData;
      const next = advanceSlot(pos, k, q);
      pos[0] = next[0]; pos[1] = next[1]; pos[2] = next[2];
      const nOri = new Array(6);
      for (let w = 0; w < 6; w++) nOri[P[w]] = ori[w];
      g.userData.ori = nOri;
      g.position.set(pos[0], pos[1], pos[2]);
      g.quaternion.premultiply(qTurn);
      g.quaternion.copy(snapQuaternion(g.quaternion));
    }
    group.remove(...affected);
    this.root.add(...affected);
    const done = this.anim.move;
    this.anim = null;
    return done;
  }

  /** Advance one frame; renders and returns whether work remains. */
  step(now) {
    if (!this.anim && this.queue.length) {
      const nx = this.queue.shift();
      this.startMove(nx.move, nx.ms, nx.onDone);
    }
    if (this.anim) {
      const a = this.anim;
      const t = Math.min(1, (now - a.start) / a.ms);
      const e = t < 0.5 ? 2 * t * t : -1 + (4 - 2 * t) * t;
      a.group.setRotationFromAxisAngle(a.axis, a.to * e);
      if (t >= 1) {
        const cb = a.onDone;
        const done = this.finishMove();
        /* the per-move callback travels with its queued item, so every move in
         * a batch updates the model — not just the last one enqueued */
        if (cb) cb(done);
        if (this.onMoveDone) this.onMoveDone(done);
      }
    }
    this.renderer.render(this.scene, this.camera);
    return this.busy;
  }

  dispose() {
    window.removeEventListener('resize', this._onResize);
    this.renderer.dispose();
  }
}
